import { AssessmentQuestion, HydroAssessment } from "./types";

export const STAGE_TITLES: Record<string, { en: string; es: string }> = {
  location: { en: "Your Location", es: "Su Ubicación" },
  environment: { en: "Your Environment", es: "Su Entorno" },
  needs: { en: "Your Water Needs", es: "Sus Necesidades de Agua" },
  sources: { en: "Your Water Sources", es: "Sus Fuentes de Agua" },
  condition: { en: "Water Condition & Safety", es: "Estado del Agua y Seguridad" },
  source_details: { en: "About Your Water Source", es: "Sobre su Fuente de Agua" },
  resources: { en: "What You Have", es: "Lo que Usted Tiene" },
  cost_maintenance: { en: "Cost & Maintenance", es: "Costo y Mantenimiento" },
  storage: { en: "Water Storage", es: "Almacenamiento de Agua" },
  priorities: { en: "Your Priorities", es: "Sus Prioridades" },
  review: { en: "Review Your Answers", es: "Revisar sus Respuestas" },
};

export const QUESTIONS: AssessmentQuestion[] = [
  // ================= STAGE 1: LOCATION =================
  {
    id: "geo_country",
    stage: "location",
    questionEn: "What country do you live in?",
    questionEs: "¿En qué país vive?",
    helpTextEn: "Select your country to help us tailor local water guidance.",
    helpTextEs: "Seleccione su país para brindarle orientación sobre agua adecuada a su región.",
    whyAskEn: "Water guidelines, common water sources, and climate patterns vary by country.",
    whyAskEs: "Las guías sobre el agua y los patrones climáticos varían según el país.",
    type: "country",
    isVisible: () => true,
  },
  {
    id: "geo_region",
    stage: "location",
    questionEn: "What state, province, or region do you live in?",
    questionEs: "¿En qué estado, provincia o región vive?",
    helpTextEn: "Type your state or province name.",
    helpTextEs: "Escriba el nombre de su estado o provincia.",
    whyAskEn: "Local regions have distinct geography and water availability.",
    whyAskEs: "Cada región tiene una geografía y disponibilidad de agua diferente.",
    type: "text",
    isVisible: (a) => Boolean(a.geography.countryCode),
  },
  {
    id: "geo_locality",
    stage: "location",
    questionEn: "What city, town, or community are you closest to?",
    questionEs: "¿Qué ciudad, pueblo o comunidad está más cerca de usted?",
    helpTextEn: "This is optional. You do not need to provide a street address.",
    helpTextEs: "Esto es opcional. No proporcione una dirección exacta.",
    whyAskEn: "Helps identify local weather patterns or municipal water context.",
    whyAskEs: "Ayuda a entender el clima o la infraestructura de la zona.",
    type: "text",
    isVisible: (a) => Boolean(a.geography.countryCode),
  },
  {
    id: "geo_setting",
    stage: "location",
    questionEn: "What kind of area do you live in?",
    questionEs: "¿En qué tipo de zona vive?",
    whyAskEn: "Helps us know if public utilities or local natural water sources are common.",
    whyAskEs: "Nos ayuda a saber si es más común el agua de red o fuentes naturales.",
    type: "single",
    options: [
      { value: "urban", labelEn: "City", labelEs: "Ciudad" },
      { value: "town", labelEn: "Small town", labelEs: "Pueblo pequeño" },
      { value: "rural", labelEn: "Rural area", labelEs: "Zona rural" },
      { value: "remote", labelEn: "Remote area", labelEs: "Zona remota" },
      { value: "temporary", labelEn: "Temporary shelter or camp", labelEs: "Refugio temporal o campamento" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => Boolean(a.geography.countryCode),
  },
  {
    id: "geo_enrichment_confirm",
    stage: "location",
    questionEn: "We found this climate & elevation info for your area. Is this correct?",
    questionEs: "Encontramos esta información sobre su zona. ¿Es correcta?",
    type: "geo_enrichment",
    isVisible: (a) => Boolean(a.geography.countryCode && !a.geography.climateConfirmed),
  },
  {
    id: "geo_elevation",
    stage: "location",
    questionEn: "Do you live in a high mountain area?",
    questionEs: "¿Vive en una zona montañosa alta?",
    helpTextEn: "Water boils at a lower temperature at high altitudes, requiring extra boiling time.",
    helpTextEs: "El agua hierve a menor temperatura en zonas altas, requiriendo más tiempo de ebullición.",
    whyAskEn: "High altitude requires longer boiling times (3 minutes instead of 1 minute) to safely kill germs.",
    whyAskEs: "En la montaña el agua debe hervir durante 3 minutos en lugar de 1 minuto para eliminar gérmenes.",
    type: "elevation",
    options: [
      { value: "no", labelEn: "No (lowland or valley)", labelEs: "No (zona baja o valle)" },
      { value: "yes", labelEn: "Yes (high altitude mountain area)", labelEs: "Sí (zona alta de montaña)" },
      { value: "numeric", labelEn: "I know my elevation", labelEs: "Sé mi altitud exacta" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => Boolean(a.geography.climateConfirmed || a.geography.setting),
  },

  // ================= STAGE 2: ENVIRONMENT =================
  {
    id: "env_weather",
    stage: "environment",
    questionEn: "What is the weather usually like where you live?",
    questionEs: "¿Cómo es el clima habitualmente donde vive?",
    helpTextEn: "Select all that apply.",
    helpTextEs: "Seleccione todas las opciones que correspondan.",
    type: "multi",
    options: [
      { value: "hot", labelEn: "Hot most of the year", labelEs: "Cálido la mayor parte del año" },
      { value: "mild", labelEn: "Mild", labelEs: "Templado" },
      { value: "cold", labelEn: "Cold", labelEs: "Frío" },
      { value: "dry", labelEn: "Very dry", labelEs: "Muy seco" },
      { value: "humid", labelEn: "Humid", labelEs: "Húmedo" },
      { value: "rainy", labelEn: "Rainy", labelEs: "Lluvioso" },
      { value: "variable", labelEn: "Changes a lot during the year", labelEs: "Cambia mucho durante el año" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "env_rain",
    stage: "environment",
    questionEn: "How often does it rain?",
    questionEs: "¿Con qué frecuencia llueve?",
    type: "single",
    options: [
      { value: "common", labelEn: "Rain is common most of the year", labelEs: "Llueve seguido casi todo el año" },
      { value: "seasonal", labelEn: "Rain comes during certain seasons", labelEs: "Llueve en temporadas específicas" },
      { value: "uncommon", labelEn: "Rain is uncommon", labelEs: "Poco común" },
      { value: "rare", labelEn: "Rain is very rare", labelEs: "Muy raro" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "env_events",
    stage: "environment",
    questionEn: "Is anything affecting water in your area right now?",
    questionEs: "¿Hay alguna situación afectando el agua en su zona actualmente?",
    helpTextEn: "Select all that apply.",
    helpTextEs: "Seleccione todas las que correspondan.",
    whyAskEn: "Emergency events like floods or broken pipes increase bacteria and require urgent steps.",
    whyAskEs: "Emergencias como inundaciones o tuberías rotas aumentan el riesgo de bacterias.",
    type: "multi",
    options: [
      { value: "drought", labelEn: "Drought", labelEs: "Sequía" },
      { value: "flooding", labelEn: "Flooding", labelEs: "Inundación" },
      { value: "storm", labelEn: "Major storm", labelEs: "Tormenta fuerte" },
      { value: "wildfire", labelEn: "Wildfire", labelEs: "Incendio forestal" },
      { value: "earthquake", labelEn: "Earthquake", labelEs: "Sismo / Terremoto" },
      { value: "broken_system", labelEn: "Broken water system", labelEs: "Sistema de agua roto" },
      { value: "shortage", labelEn: "Water shortage", labelEs: "Escasez de agua" },
      { value: "sewage_problem", labelEn: "Sewage problem", labelEs: "Problema de aguas negras" },
      { value: "none", labelEn: "Nothing unusual", labelEs: "Nada fuera de lo normal" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },

  // ================= STAGE 3: WATER NEEDS =================
  {
    id: "needs_people",
    stage: "needs",
    questionEn: "How many people need this water?",
    questionEs: "¿Cuántas personas necesitan esta agua?",
    helpTextEn: "Enter the total number of household members or community members.",
    helpTextEs: "Ingrese la cantidad total de integrantes del hogar.",
    whyAskEn: "Helps estimate how many liters of safe water you need each day.",
    whyAskEs: "Nos ayuda a calcular cuántos litros de agua segura necesita al día.",
    type: "number",
    minNumber: 1,
    maxNumber: 100,
    isVisible: () => true,
  },
  {
    id: "needs_uses",
    stage: "needs",
    questionEn: "What will you use the water for?",
    questionEs: "¿Para qué va a utilizar el agua?",
    helpTextEn: "Select all that apply.",
    helpTextEs: "Seleccione todas las opciones que correspondan.",
    whyAskEn: "Water used for drinking and cooking must meet higher safety standards than water for cleaning.",
    whyAskEs: "El agua para beber y cocinar requiere mayor desinfección que la de limpieza.",
    type: "multi",
    options: [
      { value: "drinking", labelEn: "Drinking", labelEs: "Beber" },
      { value: "cooking", labelEn: "Cooking", labelEs: "Cocinar" },
      { value: "washing_food", labelEn: "Washing food", labelEs: "Lavar alimentos" },
      { value: "brushing_teeth", labelEn: "Brushing teeth", labelEs: "Lavarse los dientes" },
      { value: "bathing", labelEn: "Bathing", labelEs: "Bañarse" },
      { value: "washing_dishes", labelEn: "Washing dishes", labelEs: "Lavar platos" },
      { value: "cleaning", labelEn: "Cleaning", labelEs: "Limpieza del hogar" },
      { value: "laundry", labelEn: "Laundry", labelEs: "Lavar ropa" },
      { value: "animals", labelEn: "Animals", labelEs: "Animales / Ganado" },
      { value: "farming", labelEn: "Gardening or farming", labelEs: "Jardín o cultivo" },
      { value: "emergency", labelEn: "Emergency use", labelEs: "Uso de emergencia" },
    ],
    isVisible: () => true,
  },
  {
    id: "needs_quantity",
    stage: "needs",
    questionEn: "How much water do you need?",
    questionEs: "¿Qué cantidad de agua necesita?",
    type: "single",
    options: [
      { value: "drinking-only", labelEn: "Only enough for drinking", labelEs: "Solo lo suficiente para beber" },
      { value: "drinking-cooking", labelEn: "Drinking and cooking", labelEs: "Para beber y cocinar" },
      { value: "household", labelEn: "Most household needs", labelEs: "La mayoría de las necesidades del hogar" },
      { value: "maximum", labelEn: "As much household water as possible", labelEs: "Tanta agua como sea posible" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "needs_urgency",
    stage: "needs",
    questionEn: "How soon do you need a solution?",
    questionEs: "¿Con qué rapidez necesita una solución?",
    whyAskEn: "If you need water today, we prioritize immediate methods like boiling or bleach over building slow filters.",
    whyAskEs: "Si necesita agua hoy, priorizamos métodos inmediatos como hervir o cloro.",
    type: "single",
    options: [
      { value: "today", labelEn: "Today (Immediate need)", labelEs: "Hoy mismo (Necesidad inmediata)" },
      { value: "days", labelEn: "Within a few days", labelEs: "En un par de días" },
      { value: "weeks", labelEn: "Within a few weeks", labelEs: "En algunas semanas" },
      { value: "planning", labelEn: "I am planning ahead", labelEs: "Estoy planificando a futuro" },
    ],
    isVisible: () => true,
  },

  // ================= STAGE 4: WATER SOURCES =================
  {
    id: "sources_available",
    stage: "sources",
    questionEn: "What water sources can you use?",
    questionEs: "¿De qué fuentes puede obtener agua?",
    helpTextEn: "Select all sources you have access to.",
    helpTextEs: "Seleccione todas las fuentes a las que tiene acceso.",
    whyAskEn: "Comparing multiple sources allows us to recommend the safest or easiest option.",
    whyAskEs: "Comparar varias fuentes nos permite recomendar la más segura y práctica.",
    type: "multi",
    options: [
      { value: "rainwater", labelEn: "Rainwater", labelEs: "Agua de lluvia" },
      { value: "well", labelEn: "Well or borehole", labelEs: "Pozo o perforación" },
      { value: "spring", labelEn: "Spring", labelEs: "Manantial" },
      { value: "river", labelEn: "River", labelEs: "Río" },
      { value: "stream", labelEn: "Stream / Creek", labelEs: "Arroyo / Quebrada" },
      { value: "lake_pond", labelEn: "Lake or pond", labelEs: "Lago o laguna" },
      { value: "piped", labelEn: "Piped or tap water", labelEs: "Agua de grifo o red" },
      { value: "public_point", labelEn: "Public water point or standpipe", labelEs: "Punto de agua público o pila" },
      { value: "truck_delivered", labelEn: "Water delivered by truck / tanker", labelEs: "Agua de camión cisterna / pipa" },
      { value: "bottled", labelEn: "Bottled water", labelEs: "Agua embotellada / garrafón" },
      { value: "other_household", labelEn: "Water from another household", labelEs: "Agua comprada o pedida a un vecino" },
      { value: "another", labelEn: "Another source", labelEs: "Otra fuente" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "sources_primary",
    stage: "sources",
    questionEn: "Which water source do you use most?",
    questionEs: "¿Cuál es la fuente de agua que más utiliza?",
    type: "single",
    isVisible: (a) => a.waterAccess.availableSources.length > 1,
  },
  {
    id: "sources_availability",
    stage: "sources",
    questionEn: "Is this water available all year?",
    questionEs: "¿Esta agua está disponible durante todo el año?",
    type: "single",
    options: [
      { value: "year-round", labelEn: "Yes, available all year", labelEs: "Sí, disponible todo el año" },
      { value: "no", labelEn: "No", labelEs: "No" },
      { value: "seasonal", labelEn: "Only during certain seasons", labelEs: "Solo en ciertas estaciones" },
      { value: "unreliable", labelEn: "It often runs out or shuts off", labelEs: "Se corta o se agota seguido" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.length > 0,
  },
  {
    id: "sources_difficulty",
    stage: "sources",
    questionEn: "How hard is it to get this water?",
    questionEs: "¿Qué tan difícil es conseguir esta agua?",
    type: "single",
    options: [
      { value: "home", labelEn: "It is directly at my home", labelEs: "Llega directo a mi casa" },
      { value: "under-10-min", labelEn: "Less than 10 minutes away", labelEs: "A menos de 10 minutos" },
      { value: "10-30-min", labelEn: "10 to 30 minutes away", labelEs: "De 10 a 30 minutos" },
      { value: "over-30-min", labelEn: "More than 30 minutes away", labelEs: "A más de 30 minutos" },
      { value: "delivered", labelEn: "Someone delivers it to me", labelEs: "Alguien la trae o la entrega" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.length > 0,
  },

  // ================= STAGE 5: WATER CONDITION & SAFETY =================
  {
    id: "cond_appearance",
    stage: "condition",
    questionEn: "What does the water look like?",
    questionEs: "¿Qué aspecto tiene el agua?",
    helpTextEn: "Select all that apply. Do not taste suspicious water.",
    helpTextEs: "Seleccione todas las opciones que correspondan. No pruebe agua sospechosa.",
    type: "multi",
    options: [
      { value: "clear", labelEn: "Clear", labelEs: "Clara y transparente" },
      { value: "cloudy", labelEn: "Cloudy", labelEs: "Nublada / Blanquecina" },
      { value: "muddy", labelEn: "Muddy or filled with dirt", labelEs: "Con barro o lodo" },
      { value: "brown", labelEn: "Brownish", labelEs: "Marrón o verdosa" },
      { value: "yellow", labelEn: "Yellowish", labelEs: "Amarillenta" },
      { value: "green", labelEn: "Green (Algae)", labelEs: "Verde (Con algas)" },
      { value: "floating_material", labelEn: "Floating dirt or particles", labelEs: "Basura o partículas flotando" },
      { value: "oily_shiny", labelEn: "Oily, shiny, or film on top", labelEs: "Aceitosa o con brillo flotante" },
      { value: "something_else", labelEn: "Something else", labelEs: "Otro aspecto" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "cond_odor",
    stage: "condition",
    questionEn: "Does the water have an unusual smell?",
    questionEs: "¿El agua tiene algún olor extraño?",
    whyAskEn: "Smells like fuel or chemicals indicate toxic risks that household filters cannot safely clean.",
    whyAskEs: "Olores a gasolina o químicos indican contaminantes tóxicos que un filtro casero no puede quitar.",
    type: "single",
    options: [
      { value: "none", labelEn: "No unusual smell", labelEs: "Sin olor extraño" },
      { value: "sewage", labelEn: "Sewage or toilet smell", labelEs: "Olor a aguas negras o drenaje" },
      { value: "rotten_egg", labelEn: "Rotten egg / Sulfur smell", labelEs: "Olor a huevo podrido / azufre" },
      { value: "fuel_gasoline", labelEn: "Fuel or gasoline smell", labelEs: "Olor a gasolina, diésel o combustible" },
      { value: "chemical", labelEn: "Chemical or factory smell", labelEs: "Olor a químicos o fábrica" },
      { value: "earthy", labelEn: "Strong earthy or swamp smell", labelEs: "Olor fuerte a tierra o pantano" },
      { value: "another", labelEn: "Another smell", labelEs: "Otro olor" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "cond_risks",
    stage: "condition",
    questionEn: "Is anything near the water source that could make it dirty or unsafe?",
    questionEs: "¿Hay algo cerca de la fuente de agua que pueda ensuciarla o contaminarla?",
    helpTextEn: "Select all that apply.",
    helpTextEs: "Seleccione todas las opciones que correspondan.",
    type: "multi",
    options: [
      { value: "toilets_sewage", labelEn: "Toilets, latrines, or sewage", labelEs: "Baños, letrinas o drenajes" },
      { value: "farm_animals", labelEn: "Farm animals or livestock", labelEs: "Animales de granja o ganado" },
      { value: "wildlife", labelEn: "Wildlife", labelEs: "Animales silvestres" },
      { value: "farms_agriculture", labelEn: "Farms or crops", labelEs: "Cultivos o parcelas agrícolas" },
      { value: "pesticides_fertilizer", labelEn: "Pesticides or fertilizers", labelEs: "Pesticidas, plaguicidas o abono" },
      { value: "factories", labelEn: "Factories or industrial plants", labelEs: "Fábricas o plantas industriales" },
      { value: "workshops", labelEn: "Mechanic workshops / Auto repair", labelEs: "Talleres mecánicos" },
      { value: "mining", labelEn: "Mining activity", labelEs: "Minería" },
      { value: "fuel_storage", labelEn: "Fuel tanks or gas stations", labelEs: "Gasolineras o tanques de combustible" },
      { value: "trash", labelEn: "Trash dumps or burning area", labelEs: "Tiraderos de basura" },
      { value: "floodwater", labelEn: "Floodwater or stagnant water", labelEs: "Agua estancada o de inundación" },
      { value: "dead_animals", labelEn: "Dead animals nearby", labelEs: "Animales muertos cerca" },
      { value: "heavy_algae", labelEn: "Heavy green algae", labelEs: "Abundantes algas verdes" },
      { value: "none", labelEn: "Nothing that I know of", labelEs: "Nada que yo sepa" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "cond_changes",
    stage: "condition",
    questionEn: "Has the water changed recently?",
    questionEs: "¿El agua ha cambiado recientemente?",
    type: "single",
    options: [
      { value: "no", labelEn: "No change", labelEs: "Sin cambios" },
      { value: "cloudy", labelEn: "Became cloudy or muddy", labelEs: "Se volvió turbia o con lodo" },
      { value: "color", labelEn: "Changed color", labelEs: "Cambió de color" },
      { value: "smell", labelEn: "Changed smell", labelEs: "Cambió de olor" },
      { value: "level", labelEn: "Water level changed drastically", labelEs: "El nivel de agua cambió drásticamente" },
      { value: "rain", labelEn: "Became worse after recent rain", labelEs: "Empeoró tras las lluvias recientes" },
      { value: "flooding", labelEn: "Became worse after flooding", labelEs: "Empeoró tras una inundación" },
      { value: "other", labelEn: "Something else", labelEs: "Otro cambio" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "safety_warning",
    stage: "condition",
    questionEn: "Has anyone told you this water may be unsafe?",
    questionEs: "¿Alguien le ha advertido que esta agua puede no ser segura?",
    type: "single",
    options: [
      { value: "no", labelEn: "No warnings", labelEs: "Sin advertencias" },
      { value: "local_authorities", labelEn: "Local authorities", labelEs: "Autoridades locales" },
      { value: "health_workers", labelEn: "Health workers or doctor", labelEs: "Personal de salud o médico" },
      { value: "community", labelEn: "People in my community", labelEs: "Vecinos o personas de la comunidad" },
      { value: "official_warning", labelEn: "Official advisory or warning sign", labelEs: "Aviso u orden oficial de alerta" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "safety_warning_detail",
    stage: "condition",
    questionEn: "What does the official warning say?",
    questionEs: "¿Qué indica la advertencia u orden oficial?",
    type: "single",
    options: [
      { value: "boil", labelEn: "Boil the water before drinking", labelEs: "Hervir el agua antes de beber" },
      { value: "do-not-drink", labelEn: "Do NOT drink the water", labelEs: "NO beber el agua" },
      { value: "do-not-use", labelEn: "Do NOT use the water for anything", labelEs: "NO usar el agua para nada" },
      { value: "other", labelEn: "Another warning", labelEs: "Otra advertencia" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.safety.warningSource === "official_warning" || a.safety.warningSource === "local_authorities",
  },
  {
    id: "safety_tested",
    stage: "condition",
    questionEn: "Has this water been tested in a laboratory?",
    questionEs: "¿Se ha analizado esta agua en un laboratorio?",
    type: "single",
    options: [
      { value: "yes", labelEn: "Yes, it was tested", labelEs: "Sí, fue analizada" },
      { value: "no", labelEn: "No", labelEs: "No" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "safety_test_results",
    stage: "condition",
    questionEn: "What did the water test find?",
    questionEs: "¿Qué encontraron en el análisis de laboratorio?",
    helpTextEn: "Select all that were reported in the test results.",
    helpTextEs: "Seleccione todo lo reportado en los resultados.",
    type: "multi",
    options: [
      { value: "bacteria", labelEn: "Bacteria / Germs / Coliforms", labelEs: "Bacterias / Gérmenes / Coliformes" },
      { value: "ecoli", labelEn: "E. coli", labelEs: "E. coli" },
      { value: "parasites", labelEn: "Parasites / Giardia / Amoebas", labelEs: "Parásitos / Giardia / Amibas" },
      { value: "arsenic", labelEn: "Arsenic", labelEs: "Arsénico" },
      { value: "lead", labelEn: "Lead", labelEs: "Plomo" },
      { value: "nitrates", labelEn: "Nitrates / Agricultural runoff", labelEs: "Nitratos" },
      { value: "fluoride", labelEn: "High Fluoride", labelEs: "Exceso de flúor" },
      { value: "salt", labelEn: "Salt / Salinity", labelEs: "Sal / Salinidad" },
      { value: "iron", labelEn: "Iron / Heavy metals", labelEs: "Hierro / Metales" },
      { value: "pesticides", labelEn: "Pesticides", labelEs: "Pesticidas / Plaguicidas" },
      { value: "other_chemical", labelEn: "Another chemical", labelEs: "Otro químico" },
      { value: "results_not_understood", labelEn: "I have the paper but do not understand it", labelEs: "Tengo los resultados pero no los entiendo" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.safety.tested === "yes",
  },

  // ================= STAGE 6: SOURCE DETAILS (BRANCHING) =================
  // RAINWATER BRANCH
  {
    id: "rain_surface",
    stage: "source_details",
    questionEn: "Where do you collect the rainwater?",
    questionEs: "¿De dónde recolecta el agua de lluvia?",
    type: "single",
    options: [
      { value: "roof", labelEn: "Roof of a home or building", labelEs: "Techo de la casa o edificación" },
      { value: "plastic_sheet", labelEn: "Plastic tarp or sheet", labelEs: "Lona o plástico extendido" },
      { value: "ground", labelEn: "Ground surface / Catchment area", labelEs: "Superficie del suelo" },
      { value: "open_containers", labelEn: "Directly into open buckets/tanks", labelEs: "Directo en tanques o cubetas abiertas" },
      { value: "other", labelEn: "Another surface", labelEs: "Otra superficie" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.includes("rainwater"),
  },
  {
    id: "rain_roof_material",
    stage: "source_details",
    questionEn: "What is the roof or collection surface made from?",
    questionEs: "¿De qué material es el techo o superficie de recolección?",
    type: "single",
    options: [
      { value: "metal", labelEn: "Corrugated metal / Tin sheet", labelEs: "Lámina galvanizada o metálica" },
      { value: "tile", labelEn: "Clay tile / Ceramic tile", labelEs: "Teja de barro o cerámica" },
      { value: "concrete", labelEn: "Concrete slab / Cement", labelEs: "Losa de concreto / Cemento" },
      { value: "plastic", labelEn: "Plastic sheet or tarp", labelEs: "Plástico o lona" },
      { value: "wood", labelEn: "Wood or thatch", labelEs: "Madera o paja" },
      { value: "other", labelEn: "Another material", labelEs: "Otro material" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.includes("rainwater"),
  },
  {
    id: "rain_first_flush",
    stage: "source_details",
    questionEn: "Do you let the first rain wash the surface before collecting water?",
    questionEs: "¿Deja que la primera lluvia lave el techo antes de juntar agua?",
    helpTextEn: "The first rain washes away dirt, dust, and animal droppings.",
    helpTextEs: "La primera lluvia limpia el polvo y los desechos de aves del techo.",
    whyAskEn: "Diverting the 'first flush' removes over 80% of contamination from roofs.",
    whyAskEs: "Desviar los primeros minutos de lluvia elimina la mayor parte del polvo y suciedad.",
    type: "single",
    options: [
      { value: "yes", labelEn: "Yes, I divert the first rain", labelEs: "Sí, desvío la primera lluvia" },
      { value: "no", labelEn: "No, I collect it immediately", labelEs: "No, la recolecto de inmediato" },
      { value: "sometimes", labelEn: "Sometimes", labelEs: "A veces" },
      { value: "unknown_meaning", labelEn: "I don't know what this means", labelEs: "No entiendo este concepto" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.includes("rainwater"),
  },
  {
    id: "rain_container_covered",
    stage: "source_details",
    questionEn: "Is the rainwater storage container covered?",
    questionEs: "¿El recipiente donde junta el agua de lluvia está tapado?",
    type: "single",
    options: [
      { value: "yes", labelEn: "Yes, completely covered with lid or mesh", labelEs: "Sí, tapado con tapa o malla" },
      { value: "no", labelEn: "No, open to air", labelEs: "No, está abierto al aire" },
      { value: "sometimes", labelEn: "Sometimes", labelEs: "A veces" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.includes("rainwater"),
  },

  // WELL / BOREHOLE BRANCH
  {
    id: "well_type",
    stage: "source_details",
    questionEn: "What kind of well is it?",
    questionEs: "¿Qué tipo de pozo es?",
    type: "single",
    options: [
      { value: "hand_dug", labelEn: "Hand-dug well (Open or shallow)", labelEs: "Pozo artesanal o cavado a mano" },
      { value: "drilled_borehole", labelEn: "Drilled well / Deep borehole with pipe", labelEs: "Pozo profundo o perforado" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.includes("well"),
  },
  {
    id: "well_covered",
    stage: "source_details",
    questionEn: "Is the top of the well covered and sealed?",
    questionEs: "¿La boca del pozo está tapada y protegida?",
    type: "single",
    options: [
      { value: "yes", labelEn: "Yes, sealed concrete pad and cover", labelEs: "Sí, brocal de concreto y tapa" },
      { value: "no", labelEn: "No, open top", labelEs: "No, está abierto" },
      { value: "partly", labelEn: "Partly covered", labelEs: "Parcialmente cubierto" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.includes("well"),
  },
  {
    id: "well_extraction",
    stage: "source_details",
    questionEn: "How do you get the water out of the well?",
    questionEs: "¿Cómo saca el agua del pozo?",
    type: "single",
    options: [
      { value: "hand_pump", labelEn: "Hand pump", labelEs: "Bomba manual" },
      { value: "electric_pump", labelEn: "Electric or solar pump", labelEs: "Bomba eléctrica o solar" },
      { value: "bucket", labelEn: "Bucket and rope", labelEs: "Balde y cuerda" },
      { value: "other", labelEn: "Another way", labelEs: "De otra manera" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.includes("well"),
  },
  {
    id: "well_flood_reached",
    stage: "source_details",
    questionEn: "Has floodwater reached or entered the well recently?",
    questionEs: "¿Ha entrado agua de inundación al pozo recientemente?",
    type: "single",
    options: [
      { value: "yes", labelEn: "Yes, floodwater reached the well", labelEs: "Sí, entró agua de inundación" },
      { value: "no", labelEn: "No", labelEs: "No" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.includes("well"),
  },

  // SPRING BRANCH
  {
    id: "spring_protected",
    stage: "source_details",
    questionEn: "Is the spring protected or covered?",
    questionEs: "¿El manantial está protegido o encajonado?",
    type: "single",
    options: [
      { value: "yes", labelEn: "Yes, protected spring box", labelEs: "Sí, tiene caja o estructura de protección" },
      { value: "no", labelEn: "No, open pool or trickle", labelEs: "No, brota al aire libre" },
      { value: "partly", labelEn: "Partly protected", labelEs: "Protegido parcialmente" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.includes("spring"),
  },

  // SURFACE WATER BRANCH (River, Stream, Lake, Pond)
  {
    id: "surface_upstream",
    stage: "source_details",
    questionEn: "What is upstream or near this surface water?",
    questionEs: "¿Qué hay río arriba o cerca de esta agua de superficie?",
    type: "multi",
    options: [
      { value: "homes", labelEn: "Homes or towns", labelEs: "Casas o poblados" },
      { value: "sewage", labelEn: "Sewage pipes or discharge", labelEs: "Descarga de aguas negras" },
      { value: "farms", labelEn: "Crops or livestock", labelEs: "Siembras o ganado" },
      { value: "factories", labelEn: "Factories or industry", labelEs: "Fábricas o industrias" },
      { value: "trash", labelEn: "Trash dumps", labelEs: "Basureros" },
      { value: "algae", labelEn: "Heavy algae scum", labelEs: "Capa gruesa de algas" },
      { value: "none", labelEn: "Nothing that I know of", labelEs: "Nada que yo sepa" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) =>
      a.waterAccess.availableSources.includes("river") ||
      a.waterAccess.availableSources.includes("stream") ||
      a.waterAccess.availableSources.includes("lake_pond"),
  },

  // PIPED WATER BRANCH
  {
    id: "piped_continuous",
    stage: "source_details",
    questionEn: "Is the piped water available continuously all day?",
    questionEs: "¿El agua de grifo llega de forma continua todo el día?",
    type: "single",
    options: [
      { value: "yes", labelEn: "Yes, 24 hours a day", labelEs: "Sí, las 24 horas" },
      { value: "no", labelEn: "No, only a few hours per day", labelEs: "No, solo unas horas al día" },
      { value: "often_shuts_off", labelEn: "It shuts off for days at a time", labelEs: "Se corta por varios días" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.waterAccess.availableSources.includes("piped"),
  },

  // ================= STAGE 7: RESOURCES =================
  {
    id: "res_materials",
    stage: "resources",
    questionEn: "What materials do you already have?",
    questionEs: "¿Con qué materiales cuenta actualmente en su hogar?",
    helpTextEn: "Select all that you currently have on hand.",
    helpTextEs: "Seleccione todo lo que tenga disponible.",
    type: "multi",
    options: [
      { value: "buckets", labelEn: "Clean buckets or pots", labelEs: "Cubetas o ollas limpias" },
      { value: "lidded_containers", labelEn: "Containers with tight lids / Jugs", labelEs: "Garrafones o bidones con tapa" },
      { value: "bottles", labelEn: "Plastic or glass water bottles", labelEs: "Botellas de agua" },
      { value: "large_tank", labelEn: "Large water tank / Rotoplas / Barrel", labelEs: "Tanque grande, tinaco o tambo" },
      { value: "clean_cloth", labelEn: "Clean cotton cloth or bedsheet", labelEs: "Tela de algodón o sábana limpia" },
      { value: "metal_pot", labelEn: "Metal pot for boiling water", labelEs: "Olla de metal para hervir agua" },
      { value: "sand", labelEn: "Clean sand", labelEs: "Arena limpia" },
      { value: "gravel", labelEn: "Clean gravel or small pebbles", labelEs: "Grava o piedras pequeñas" },
      { value: "activated_charcoal", labelEn: "Plain crushed charcoal (no chemicals)", labelEs: "Carbón vegetal triturado (sin químicos)" },
      { value: "ceramic_filter", labelEn: "Ceramic filter pot or candle", labelEs: "Filtro cerámico o de vela" },
      { value: "commercial_filter", labelEn: "Commercial water filter pitcher or unit", labelEs: "Filtro comercial o purificador" },
      { value: "purification_tablets", labelEn: "Water purification tablets", labelEs: "Pastillas purificadoras de agua" },
      { value: "bleach", labelEn: "Plain unscented household bleach", labelEs: "Cloro común sin aroma (blanqueador)" },
      { value: "clear_pet_bottles", labelEn: "Clear transparent plastic PET bottles", labelEs: "Botellas plásticas PET transparentes" },
      { value: "tubing_hose", labelEn: "Plastic tubing or hose", labelEs: "Manguera o tubo de plástico" },
      { value: "spigot_faucet", labelEn: "Faucet / Spigot tap", labelEs: "Grifo, llave o canilla" },
      { value: "none", labelEn: "None of these", labelEs: "Ninguno de estos" },
    ],
    isVisible: () => true,
  },
  {
    id: "res_utilities",
    stage: "resources",
    questionEn: "What power or heat sources do you have available?",
    questionEs: "¿Qué fuentes de energía o calor tiene disponibles?",
    type: "multi",
    options: [
      { value: "electricity_full", labelEn: "Electricity all day", labelEs: "Electricidad las 24 horas" },
      { value: "electricity_partial", labelEn: "Electricity sometimes", labelEs: "Electricidad por horas" },
      { value: "gas_stove", labelEn: "Gas stove / Propane burner", labelEs: "Estufa de gas / Estufón" },
      { value: "wood_fire", labelEn: "Wood fire or fogón", labelEs: "Fuego de leña / Fogón" },
      { value: "charcoal_fire", labelEn: "Charcoal stove", labelEs: "Anafre / Carbón" },
      { value: "cooking_fuel", labelEn: "Kerosene or other cooking fuel", labelEs: "Otro combustible para cocinar" },
      { value: "strong_sunlight", labelEn: "Strong direct sunlight", labelEs: "Sol directo y fuerte" },
      { value: "none", labelEn: "None of these", labelEs: "Ninguna de estas" },
    ],
    isVisible: () => true,
  },
  {
    id: "res_tools",
    stage: "resources",
    questionEn: "What tools can you use if construction is needed?",
    questionEs: "¿Con qué herramientas cuenta si necesita armar algo?",
    type: "multi",
    options: [
      { value: "no_tools", labelEn: "No tools", labelEs: "Sin herramientas" },
      { value: "knife_scissors", labelEn: "Knife or scissors", labelEs: "Cuchillo o tijeras" },
      { value: "hammer", labelEn: "Hammer", labelEs: "Martillo" },
      { value: "drill", labelEn: "Drill", labelEs: "Taladro" },
      { value: "saw", labelEn: "Saw", labelEs: "Sierra / Serrucho" },
      { value: "hand_tools", labelEn: "Basic hand tools (Pliers, Screwdriver)", labelEs: "Herramientas básicas (Pinzas, Desarmador)" },
      { value: "power_tools", labelEn: "Power tools", labelEs: "Herramientas eléctricas" },
      { value: "someone_can_help", labelEn: "Someone in my community can help me with tools", labelEs: "Alguien en mi comunidad me puede prestar herramientas" },
    ],
    isVisible: () => true,
  },
  {
    id: "res_space",
    stage: "resources",
    questionEn: "How much space do you have for a water system?",
    questionEs: "¿De cuánto espacio dispone para colocar un sistema de agua?",
    type: "single",
    options: [
      { value: "minimal", labelEn: "Very little space (Tabletop only)", labelEs: "Muy poco espacio (Solo una mesa)" },
      { value: "bucket", labelEn: "Space for a bucket-sized system", labelEs: "Espacio para un sistema del tamaño de una cubeta" },
      { value: "large-container", labelEn: "Space for a barrel or large tank", labelEs: "Espacio para un tambo o tanque grande" },
      { value: "outdoor", labelEn: "Outdoor yard or roof space", labelEs: "Patio exterior o techo" },
      { value: "large", labelEn: "Plenty of space", labelEs: "Mucho espacio disponible" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },

  // ================= STAGE 8: COST & MAINTENANCE =================
  {
    id: "cost_budget",
    stage: "cost_maintenance",
    questionEn: "How much can you spend right now on water treatment?",
    questionEs: "¿Cuánto dinero puede invertir en este momento?",
    type: "single",
    options: [
      { value: "minimal", labelEn: "Almost nothing (Must use items at home)", labelEs: "Casi nada (Solo cosas que tenga en casa)" },
      { value: "low", labelEn: "A small amount (Under $15 USD equivalent)", labelEs: "Poco dinero (Algo económico)" },
      { value: "moderate", labelEn: "A moderate amount ($15 to $50 USD equivalent)", labelEs: "Una cantidad moderada" },
      { value: "flexible", labelEn: "I can buy equipment if needed", labelEs: "Puedo comprar equipo si es necesario" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "cost_fin_priority",
    stage: "cost_maintenance",
    questionEn: "What matters more regarding cost?",
    questionEs: "¿Qué prefiere respecto al costo?",
    type: "single",
    options: [
      { value: "lowest_cost", labelEn: "Lowest cost possible right now", labelEs: "El menor costo posible ahora mismo" },
      { value: "quality_durable", labelEn: "Spending a little more for something durable", labelEs: "Invertir un poco más en algo duradero" },
      { value: "unsure", labelEn: "I am not sure", labelEs: "No estoy seguro/a" },
    ],
    isVisible: () => true,
  },
  {
    id: "maint_time",
    stage: "cost_maintenance",
    questionEn: "How much time can you spend treating water each day?",
    questionEs: "¿Cuánto tiempo puede dedicar a tratar el agua cada día?",
    type: "single",
    options: [
      { value: "under-5", labelEn: "Less than 5 minutes", labelEs: "Menos de 5 minutos" },
      { value: "5-15", labelEn: "5 to 15 minutes", labelEs: "De 5 a 15 minutos" },
      { value: "15-30", labelEn: "15 to 30 minutes", labelEs: "De 15 a 30 minutos" },
      { value: "over-30", labelEn: "More than 30 minutes", labelEs: "Más de 30 minutos" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "maint_capacity",
    stage: "cost_maintenance",
    questionEn: "How much maintenance work can you manage?",
    questionEs: "¿Qué nivel de mantenimiento puede realizar?",
    type: "single",
    options: [
      { value: "minimal", labelEn: "Very little maintenance", labelEs: "Mantenimiento mínimo" },
      { value: "simple", labelEn: "Simple washing of cloth / containers", labelEs: "Lavado sencillo de telas y vasijas" },
      { value: "regular", labelEn: "Regular washing and sand scrubbing", labelEs: "Limpieza periódica de filtros y arena" },
      { value: "replace-materials", labelEn: "Cleaning and replacing filter materials", labelEs: "Reemplazo regular de repuestos y carbón" },
      { value: "advanced", labelEn: "I can maintain a complex system", labelEs: "Puedo mantener un sistema más complejo" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "maint_replacements",
    stage: "cost_maintenance",
    questionEn: "Can you regularly get replacement materials locally?",
    questionEs: "¿Puede conseguir repuestos o insumos en su localidad?",
    type: "single",
    options: [
      { value: "yes", labelEn: "Yes, easily in local stores or markets", labelEs: "Sí, fácilmente en tiendas o mercados" },
      { value: "maybe", labelEn: "Maybe, with effort", labelEs: "Tal vez, con algo de esfuerzo" },
      { value: "no", labelEn: "No, supplies are very hard to find", labelEs: "No, es muy difícil conseguir insumos" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },

  // ================= STAGE 9: STORAGE =================
  {
    id: "storage_type",
    stage: "storage",
    questionEn: "How do you currently store water at home?",
    questionEs: "¿Cómo almacena actualmente el agua en su hogar?",
    type: "single",
    options: [
      { value: "none", labelEn: "I do not store it (Use immediately)", labelEs: "No la almaceno (La uso de inmediato)" },
      { value: "open_bucket", labelEn: "Open bucket or pot", labelEs: "Cubeta o balde abierto" },
      { value: "covered_bucket", labelEn: "Covered bucket with lid", labelEs: "Cubeta con tapa" },
      { value: "bottle", labelEn: "Closed plastic bottles or jugs", labelEs: "Botellas o garrafones cerrados" },
      { value: "container_with_lid", labelEn: "Clean container with tight lid & tap", labelEs: "Recipiente limpio con tapa y llave" },
      { value: "large_tank", labelEn: "Large covered water tank / Rotoplas", labelEs: "Tanque grande o tinaco cerrado" },
      { value: "other", labelEn: "Another container", labelEs: "Otro recipiente" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: () => true,
  },
  {
    id: "storage_withdrawal",
    stage: "storage",
    questionEn: "How do you take water out of the storage container?",
    questionEs: "¿Cómo saca el agua del recipiente de almacenamiento?",
    whyAskEn: "Dipping cups or hands into stored water re-contaminates safe drinking water.",
    whyAskEs: "Meter tazas o manos al agua tratada la vuelve a contaminar con bacterias.",
    type: "single",
    options: [
      { value: "pour", labelEn: "Pour it out carefully", labelEs: "Inclinando el recipiente para servir" },
      { value: "spigot", labelEn: "Using a faucet or spigot tap at the bottom", labelEs: "Mediante un grifo o llave en la base" },
      { value: "cup_scoop", labelEn: "Using a cup, ladle, or scoop", labelEs: "Usando una taza, jarro o cucharón" },
      { value: "hands_touch", labelEn: "Hands sometimes touch or dip into water", labelEs: "A veces se introducen las manos al tomar agua" },
      { value: "other", labelEn: "Another way", labelEs: "De otra manera" },
      { value: "unknown", labelEn: "I don't know", labelEs: "No lo sé" },
    ],
    isVisible: (a) => a.storage.type !== "none",
  },

  // ================= STAGE 10: PRIORITIES =================
  {
    id: "pref_priorities",
    stage: "priorities",
    questionEn: "What matters most to you in your water plan?",
    questionEs: "¿Qué es lo más importante para usted en su plan de agua?",
    helpTextEn: "Select up to TWO priorities.",
    helpTextEs: "Seleccione hasta DOS prioridades.",
    type: "multi",
    maxSelections: 2,
    options: [
      { value: "lowest_cost", labelEn: "Lowest cost possible", labelEs: "El menor costo posible" },
      { value: "best_safety", labelEn: "Best appropriate safety option", labelEs: "La mayor desinfección y seguridad" },
      { value: "easy_to_build", labelEn: "Easy to build", labelEs: "Fácil de armar" },
      { value: "easy_to_use", labelEn: "Easy to use daily", labelEs: "Fácil de usar día a día" },
      { value: "little_fuel", labelEn: "Uses little fuel", labelEs: "Gasta poco combustible / gas" },
      { value: "no_electricity", labelEn: "Uses no electricity", labelEs: "No requiere electricidad" },
      { value: "works_quickly", labelEn: "Works quickly", labelEs: "Rápido de preparar" },
      { value: "little_maintenance", labelEn: "Needs little maintenance", labelEs: "Requiere poco mantenimiento" },
      { value: "uses_own_materials", labelEn: "Uses materials I already have", labelEs: "Usa cosas que ya tengo" },
      { value: "more_volume", labelEn: "Can provide large volume of water", labelEs: "Genera abundante agua" },
    ],
    isVisible: () => true,
  },
];
